import type { BootLine } from "../types";

export const BOOT_SEQUENCE: BootLine[] = [
  { text: "mvn quarkus:dev -Dquarkus.profile=dev", type: "prompt", delay: 0 },
  { text: "[INFO] Scanning for projects...", type: "info", delay: 400 },
  { text: "[INFO] BUILD: Resolving dependencies", type: "info", delay: 700 },
  { text: "[INFO] Compiling Java sources (Java 25)", type: "info", delay: 1000 },
  { text: "", type: "blank", delay: 1200 },
  { text: String.raw`  ____  __  __    _    ____  _  ___   _ ____  `, type: "banner", delay: 1300 },
  { text: String.raw` / __ \/ / / /   / \  |  _ \| |/ / | | / ___| `, type: "banner", delay: 1370 },
  { text: String.raw`| |  | | | | |  / _ \ | |_) | ' /| | | \___ \ `, type: "banner", delay: 1440 },
  { text: String.raw`| |__| | |_| | / ___ \|  _ <| . \| |_| |___) |`, type: "banner", delay: 1510 },
  { text: String.raw` \___\_\\___/ /_/   \_\_| \_\_|\_\\___/|____/ `, type: "banner", delay: 1580 },
  { text: String.raw`  Powered by Quarkus 3.32.3  (java 25)`, type: "bannersub", delay: 1650 },
  { text: "", type: "blank", delay: 1780 },
  { text: "Runtime   :: GraalVM CE 25.0.2+13-jvmci-23.1-b30", type: "kv", delay: 1830 },
  { text: "Profile   :: dev  |  Env :: local", type: "kv", delay: 1960 },
  { text: "PID       :: 91247", type: "kv", delay: 2060 },
  { text: "", type: "blank", delay: 2150 },
  { text: "Scanning CDI beans...", type: "section", delay: 2200 },
  { text: "  ✓  CreateOrderService       [@ApplicationScoped]", type: "success", delay: 2360 },
  { text: "  ✓  OrderRepository          [@ApplicationScoped]", type: "success", delay: 2500 },
  { text: "  ✓  PaymentGatewayAdapter    [@ApplicationScoped]", type: "success", delay: 2640 },
  { text: "  ✓  KafkaOrderProducer       [@ApplicationScoped]", type: "success", delay: 2780 },
  { text: "  ✓  JwtAuthFilter            [@Provider]", type: "success", delay: 2880 },
  { text: "  → 5 beans wired, 0 errors", type: "info", delay: 3020 },
  { text: "", type: "blank", delay: 3120 },
  { text: "Configuring datasources...", type: "section", delay: 3170 },
  { text: "  ✓  <default>  PostgreSQL 15  HikariCP (pool: 10)", type: "success", delay: 3310 },
  { text: "  ✓  Flyway migrations applied  (V8__add_order_status.sql)", type: "success", delay: 3450 },
  { text: "", type: "blank", delay: 3540 },
  { text: "Registered JAX-RS endpoints:", type: "section", delay: 3590 },
  { text: "  POST  /api/orders              CreateOrderResource", type: "endpoint", delay: 3730 },
  { text: "  GET   /api/orders/{id}         FindOrderResource", type: "endpoint", delay: 3820 },
  { text: "  PATCH /api/orders/{id}/cancel  CancelOrderResource", type: "endpoint", delay: 3910 },
  { text: "  GET   /q/health/ready          HealthCheckResource", type: "endpoint", delay: 4000 },
  { text: "", type: "blank", delay: 4090 },
  { text: "💡 Native image available  →  mvn package -Pnative", type: "hint", delay: 4140 },
  { text: "", type: "blank", delay: 4280 },
  { text: "──────────────────────────────────────────────────", type: "dim", delay: 4330 },
  { text: "✶  Listening on  http://localhost:8080", type: "ready", delay: 4460 },
  { text: "   Tests        http://localhost:8080/q/dev-ui", type: "readysub", delay: 4550 },
  { text: "   Started in   0.847s  (JVM mode)", type: "readysub", delay: 4640 },
  { text: "──────────────────────────────────────────────────", type: "dim", delay: 4730 },
];

export const LINE_COLORS: Record<string, string> = {
  prompt:    "text-terminal-green",
  info:      "text-muted-foreground",
  dim:       "text-terminal-dim",
  blank:     "",
  banner:    "text-terminal-yellow",
  bannersub: "text-terminal-amber",
  kv:        "text-terminal-cyan",
  section:   "text-terminal-purple",
  success:   "text-terminal-green",
  endpoint:  "text-terminal-cyan",
  hint:      "text-terminal-hint",
  ready:     "text-terminal-green font-semibold",
  readysub:  "text-muted-foreground",
};

export const codeLines: string[] = [
  '// ── Presentation Layer ──────────────────',
  '@Path("/api/orders")',
  '@Produces(MediaType.APPLICATION_JSON)',
  '@Consumes(MediaType.APPLICATION_JSON)',
  'public class CreateOrderResource {',
  '',
  '    @POST',
  '    public Response handle(CreateOrderRequest req) {',
  '        var cmd = req.toCommand();',
  '        Order order = createOrder.execute(cmd);',
  '        return Response.status(201).entity(order).build();',
  '    }',
  '}',
  '',
  '// ── Application Layer ───────────────────',
  '@ApplicationScoped',
  'public class CreateOrderService {',
  '',
  '    @Transactional',
  '    public Order execute(CreateOrderCommand cmd) {',
  '        LOG.info("Creating order: {}", cmd.id());',
  '        Order order = Order.create(cmd);',
  '        repository.save(order);',
  '        return order;',
  '    }',
  '}',
  '',
  '// ── Domain Layer ────────────────────────',
  'public class Order extends AggregateRoot {',
  '',
  '    public static Order create(CreateOrderCommand cmd) {',
  '        var order = new Order(OrderId.generate(), cmd.customerId());',
  '        order.raise(new OrderCreatedEvent(order.id()));',
  '        return order;',
  '    }',
  '',
  '    public void cancel() {',
  '        if (this.status.isFinal()) throw new InvalidOrderStateException();',
  '        this.status = OrderStatus.CANCELLED;',
  '        raise(new OrderCancelledEvent(this.id));',
  '    }',
  '}',
  '',
  '// ── Infrastructure Layer ────────────────',
  '@ApplicationScoped',
  'public class PanacheOrderRepository implements OrderRepository {',
  '',
  '    @Override',
  '    public void save(Order order) {',
  '        entityManager.persist(order);',
  '    }',
  '',
  '    @Override',
  '    public Optional<Order> findById(OrderId id) {',
  '        return find("id", id.value()).firstResultOptional();',
  '    }',
  '}',
  '',
];

